[project]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = [
    {name = "alandamatta",email = "alandamatta@live.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "notebook (>=7.5.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
